<?xml version="1.0" encoding="utf-8"?><Database Name="hos" Class="prodclassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=dbs;Initial Catalog=hos;User ID=mm;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="hosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="USER_ID" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="mob" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="USER_TYPE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="User_login" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="User_Password" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RIGHTS" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="CTR_NO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BR_NO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[LEVEL]" Member="LEVEL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DATE1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DSK1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="branch" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="cashier" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ad" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.command" Member="commands">
    <Type Name="command">
      <Column Name="id_user" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id_form" Type="System.Double" DbType="float" CanBeNull="true" />
      <Column Name="form_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="showform" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="cmdadd" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="cmddelete" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="cmdedit" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="cmdprint" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.categ_post" Member="categ_posts">
    <Type Name="categ_post">
      <Column Name="CATEGORY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="acc_code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="def_user" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="post_rem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="ser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="int_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sale8" Member="sale8s">
    <Type Name="sale8">
      <Column Name="auto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BRANCH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOC_NO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BILL_NO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOC_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DOC_TYPE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="partname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QTY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="barcode" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CATEGORY" Type="System.Int32" CanBeNull="true" />
      <Column Name="PARTNO" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SALE2" Member="SALE2s">
    <Type Name="SALE2">
      <Column Name="br_id" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DOC_NO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PARTNO" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="formno" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DOC_TYPE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOC_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QTY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="partname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="unit_qty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="exp_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="br_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="batch" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="typ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rem2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="scode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="categ_post" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sale7" Member="sale7s">
    <Type Name="sale7">
      <Column Name="BRANCH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOC_NO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOC_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DOC_TYPE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="SCODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DISCOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cont_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cont_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vou_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="post" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ta_sl" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="typ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ta_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ta_rem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="old_doc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="req_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mem_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="part" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pay_amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="part_end" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="part_end_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="part_end_rem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="end_user" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="doc_req" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Einv1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="e_inv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Einv1" Member="Einv1s">
    <Type Name="Einv1">
      <Column Name="inv_no" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uuId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="transDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sendDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="transUser" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="sendUser" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="send" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="issType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="issName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="issBranchId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issCountry" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="issGovernate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issStreet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issBuilding" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="recType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="recName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="recId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="recCountry" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="recGovernate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="recCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="recStreet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="recBuilding" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="documentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="documentTypeVersion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dateTimeIssued" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="taxpayerActivityCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="internalId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="totalSalesAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="totalDiscountAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="netAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="taxTotalsType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="taxTotalsAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="extraDiscountAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="totalItemsDiscountAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="totalAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="source" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cont" Type="System.Int32" CanBeNull="true" />
      <Column Name="Doc_No" Type="System.Int32" CanBeNull="true" />
      <Column Name="Gl_Name" Type="System.String" CanBeNull="true" />
      <Column Name="status" Type="System.String" CanBeNull="true" />
      <Column Name="old_uuId" Type="System.String" CanBeNull="true" />
      <Column Name="uuid_test" Type="System.String" CanBeNull="true" />
      <Column Name="old_date" Type="System.DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Einv2" Member="Einv2s">
    <Type Name="Einv2">
      <Column Name="inv_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="itemType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="itemCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="unitType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="currencySold" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="amountEGP" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="salesTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="valueDifference" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="totalTaxableFees" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="netTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="itemsDiscount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="discountRate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="internalCode" Type="System.String" CanBeNull="false" />
      <Column Name="returned" Type="System.Boolean" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Form_name" Member="Form_names">
    <Type Name="Form_name">
      <Column Name="id_form" Type="System.Double" DbType="float" CanBeNull="true" />
      <Column Name="form_name" Member="form_name1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="form_caption" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sw_pkg" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.h_data" Member="h_datas">
    <Type Name="h_data">
      <Column Name="auto_no" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DOC_NO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id_form" Type="System.Double" DbType="float" CanBeNull="true" />
      <Column Name="cmd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="form_caption" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="from_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="date1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="computer_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.COMPANY" Member="COMPANies">
    <Type Name="COMPANY">
      <Column Name="CO_NAME_E" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CO_ADD1_E" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CO_ADD2_E" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CO_PHON_E" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CO_NAME_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CO_ADD1_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CO_ADD2_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CO_PHON_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIR_NAME" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="co_tax_reg" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="tax_cent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tax_br" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="tax_typ" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tax_act_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tax_gov" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tax_city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tax_st" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tax_build_no" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tax_client_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tax_client_secret" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Einv_Prod" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Einv_Signer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="E_Pswd" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Env_st_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GLCODE" Member="GLCODEs">
    <Type Name="GLCODE">
      <Column Name="fix" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="GL_code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GL_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CONTACT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OP_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tax" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="OT_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="cont_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="post" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="nt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ta_sl" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ta_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ta_rem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dr_cr" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="e_inv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="uuid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="einv1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nt2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PCODE" Type="System.Int32" CanBeNull="true" />
      <Column Name="einv2" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="email" Type="System.String" CanBeNull="true" />
      <Column Name="old_cont_type" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stat1" Member="stat1s">
    <Type Name="stat1">
      <Column Name="no" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gl_code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="desc1" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="desc2" Type="System.String" DbType="NChar(60)" CanBeNull="true" />
      <Column Name="amount1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="amount2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ser_cat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ser_einv" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTACT" Member="CONTACTs">
    <Type Name="CONTACT">
      <Column Name="CONT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tax" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="rem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="government" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="building_no" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="tax_type" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="tax_id" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="E_inv_cont_type" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.categ_einv" Member="categ_einvs">
    <Type Name="categ_einv">
      <Column Name="CATEGORY" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="acc_code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="def_user" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="base" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="int_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SALE1" Member="SALE1s">
    <Type Name="SALE1">
      <Column Name="br_id" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DOC_NO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="formno" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="BILL_NO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOC_TYPE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DOC_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BR_NO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SCODE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Sname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DISC_RATE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DISCOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TAX1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tax2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="post" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="vou_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="post_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="br_id_fromNAME" Type="System.String" DbType="NChar(35)" CanBeNull="true" />
      <Column Name="br_id_toname" Type="System.String" DbType="NChar(35)" CanBeNull="true" />
      <Column Name="post_USER" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="cash_pay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="cash_pay_doc_no" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="out_close_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ta_sl" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ta_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="req_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="einv1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="e_inv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.pat_code" Member="pat_codes">
    <Type Name="pat_code">
      <Column Name="PCODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_NO" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="mal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BIRTH_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="patin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Einv3" Member="Einv3s">
    <Type Name="Einv3">
      <Column Name="inv_no" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uuId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="transDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sendDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="transUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sendUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="send" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="issType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="issName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="issBranchId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issCountry" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="issGovernate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issStreet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="issBuilding" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="recType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="recName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="recId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="recCountry" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="recGovernate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="recCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="recStreet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="recBuilding" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="documentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="documentTypeVersion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dateTimeIssued" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="taxpayerActivityCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="internalId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="totalSalesAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="totalDiscountAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="netAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="taxTotalsType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="taxTotalsAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="extraDiscountAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="totalItemsDiscountAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="totalAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="source" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cont" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Doc_No" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gl_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="old_uuId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="reference" Type="System.String" CanBeNull="true" />
      <Column Name="ref_inv_no" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Einv4" Member="Einv4s">
    <Type Name="Einv4">
      <Column Name="inv_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="itemType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="itemCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="unitType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="currencySold" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="amountEGP" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="salesTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="valueDifference" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="totalTaxableFees" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="netTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="itemsDiscount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="internalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="discountRate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[1100temp_1585]" Member="_1100temp_1585s">
    <Type Name="_1100temp_1585">
      <Column Name="gl_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[1100temp_429]" Member="_1100temp_429s">
    <Type Name="_1100temp_429">
      <Column Name="gl_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[1100temp_1585]" Member="_1100temp_15851s">
    <Type Name="_1100temp_15851">
      <Column Name="gl_code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ser_inv_disc2" Member="ser_inv_disc2s">
    <Type Name="ser_inv_disc2">
      <Column Name="gl_code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="amt1" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.proc1" Method="proc1">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.proc2" Method="proc2">
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updatestat1nullser_einv" Method="updatestat1nullser_einv">
    <Return Type="System.Int32" />
  </Function>
</Database>